source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"

target :ImageViewer do
    pod 'AFNetworking', '~>3.0'
    pod 'Masonry', '0.6.1' #autolayout解析
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYWebImage'
    pod 'Mantle', '~>1.5.8'
end
